### ISSUE TITLE
Did not work

### ISSUE THREAD

**Issue by Ibrahim-Khayat** [KhaledMAlasmari/KAU-schedule-generator#1] opened 2022-11-14 22:17 UTC
UnicodeEncodeError: 'charmap' codec can't encode character '\u0654' in position 315: character maps to <undefined>

**Comment by KhaledMAlasmari** [comment] 2022-11-15 10:35
Hello,

Could you please provide me with the courses ids/links?
Also, make sure you're installing dependencies through requirements.txt

**Comment by Ibrahim-Khayat** [comment] 2022-11-15 13:04
I did not change the course links written in the original code.
I installed dependencies through requirements.txt.

> Hello,
> 
> Could you please provide me with the courses ids/links? Also, make sure you're installing dependencies through requirements.txt

**Comment by KhaledMAlasmari** [comment] 2022-11-15 13:57
Ah! I got it.
It seems to me that there's an encoding issue here
I've pushed a fix to it.
Could you please try it?
Thank you

**Comment by Ibrahim-Khayat** [comment] 2022-11-15 15:05
> 

Thanks for responding. Yet, another error has appeared,
`UnicodeEncodeError: 'charmap' codec can't encode character '\u0654' in position 253: character maps to <undefined>`

**Comment by KhaledMAlasmari** [comment] 2022-11-15 21:37
That's weird. I can't reproduce the bug on my end or my friend's machine.

For some reason the program is trying to encode arabic letters in Unicode.
Perhaps it's caused by the print statements (?)

Could you please tell me your python version, and post the full error message?
Sorry for the trouble.

**Closed as completed** 2023-01-01 21:19 UTC
